"use strict";
// Spec 6 Part D — 30-theme launch rotation, from the channel's content pillars.
module.exports = [
  "grinding in obscurity",
  "building wealth alone",
  "refusing the 9 to 5",
  "figuring it out with no roadmap",
  "the compounding power of daily action",
  "financial freedom through the internet",
  "one income stream becomes many",
  "surviving the gap between starting and succeeding",
  "the cost of staying comfortable",
  "nobody is coming to save you",
  "building while broke",
  "the internet rewards the consistent",
  "one decision changes everything",
  "working while the world sleeps",
  "your network is your net worth",
  "the unsexy truth about online income",
  "small moves compound into empires",
  "betting on yourself",
  "the loneliness of building something real",
  "digital leverage changes the math",
  "from zero to one income stream",
  "the gap between knowing and doing",
  "momentum is built in private",
  "every empire started as a side project",
  "the day you stop waiting for permission",
  "building in the dark",
  "what separates starters from finishers",
  "the price of freedom is discipline",
  "online business is the great equalizer",
  "the grind is the goal",
];
